# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

WORKDIR /app

# Copy manifest and config files
COPY package*.json tsconfig.json ./

# Install dependencies without running any prepare scripts
RUN npm install --ignore-scripts --no-optional

# Copy remaining source
COPY . .

# Fetch catalogs and build project
RUN npm run fetch-catalogs && npm run build

# Default command
CMD ["node", "dist/index.js"]
